const PDFDocument = require('pdfkit');
const { prisma } = require('../config/db');

const NAAC_BLUE = '#003580';
const LIGHT_BLUE = '#E8F0FE';
const GREY = '#F8F9FF';

/**
 * Generate a professional NAAC PDF report for a teacher using PDFKit.
 * Includes HOD signature block at the end.
 */
async function generateTeacherPdf(teacherId) {
  const user = await prisma.user.findUnique({ where: { id: teacherId } });
  if (!user) throw new Error('User not found');

  // Fetch HOD for signature
  const hod = await prisma.user.findFirst({ where: { role: 'hod' } });

  const criteria = await prisma.criterion.findMany({
    orderBy: { id: 'asc' },
    include: { subCriteria: { orderBy: { code: 'asc' } } },
  });

  const submissions = await prisma.formSubmission.findMany({
    where: { teacherId },
    include: { subCriterion: true, documents: true },
  });

  const subMap = {};
  submissions.forEach((s) => { subMap[s.subCriteriaId] = s; });

  const exportDate = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
  });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 60, left: 50, right: 50 },
      info: {
        Title: `NAAC Documentation — ${user.fullName}`,
        Author: 'NAAC File Management System',
        Subject: 'NAAC Accreditation Report',
      },
    });

    const buffers = [];
    doc.on('data', (b) => buffers.push(b));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // ── Helper functions ──────────────────────────────────────
    function addHeader(text, fontSize = 14) {
      doc.rect(doc.x, doc.y, pageWidth, 28).fill(NAAC_BLUE);
      doc.fillColor('#FFFFFF').fontSize(fontSize).font('Helvetica-Bold')
        .text(text, doc.x + 10, doc.y - 28 + 7, { width: pageWidth - 20 });
      doc.fillColor('#000000').moveDown(0.5);
    }

    function addSubHeader(text) {
      doc.fontSize(11).font('Helvetica-Bold').fillColor(NAAC_BLUE)
        .text(text);
      doc.moveTo(doc.x, doc.y).lineTo(doc.x + pageWidth, doc.y)
        .strokeColor('#DDDDDD').stroke();
      doc.moveDown(0.3);
    }

    function checkPage(needed = 80) {
      if (doc.y + needed > doc.page.height - doc.page.margins.bottom) {
        doc.addPage();
      }
    }

    function drawTableRow(cells, widths, isHeader = false, altBg = false) {
      checkPage(22);
      const startX = doc.x;
      const startY = doc.y;
      const rowH = 18;

      if (isHeader) {
        doc.rect(startX, startY, pageWidth, rowH).fill(LIGHT_BLUE);
      } else if (altBg) {
        doc.rect(startX, startY, pageWidth, rowH).fill(GREY);
      }

      let x = startX;
      cells.forEach((text, i) => {
        const w = widths[i];
        doc.rect(x, startY, w, rowH).stroke();
        doc.fillColor('#000000')
          .fontSize(isHeader ? 9 : 8.5)
          .font(isHeader ? 'Helvetica-Bold' : 'Helvetica')
          .text(String(text || '—'), x + 4, startY + 4, { width: w - 8, height: rowH - 4, lineBreak: false });
        x += w;
      });

      doc.y = startY + rowH;
    }

    // ── COVER PAGE ────────────────────────────────────────────
    doc.moveDown(6);

    // Logo circle
    const cx = doc.page.width / 2;
    doc.circle(cx, doc.y + 30, 35).fill(NAAC_BLUE);
    doc.fillColor('#FFFFFF').fontSize(28).font('Helvetica-Bold')
      .text('N', cx - 12, doc.y + 16, { width: 25 });
    doc.fillColor('#000000').moveDown(4);

    doc.fontSize(24).font('Helvetica-Bold').fillColor(NAAC_BLUE)
      .text('NAAC ACCREDITATION', { align: 'center' });
    doc.fontSize(20).text('DOCUMENTATION REPORT', { align: 'center' });
    doc.moveDown(1.5);

    doc.fontSize(14).font('Helvetica').fillColor('#555555')
      .text(user.department || 'Department of Computer Engineering', { align: 'center' });
    doc.moveDown(1);

    doc.fontSize(18).font('Helvetica-Bold').fillColor('#1a1a2e')
      .text(user.fullName, { align: 'center' });
    doc.fontSize(12).font('Helvetica').fillColor('#666666')
      .text(user.designation || 'Faculty', { align: 'center' });
    doc.moveDown(3);

    doc.fontSize(10).fillColor('#888888')
      .text(`Academic Period: 2016-17 to 2020-21`, { align: 'center' });
    doc.text(`Date of Export: ${exportDate}`, { align: 'center' });
    doc.text(`Generated by NAAC File Management System`, { align: 'center' });

    // ── SUMMARY PAGE ──────────────────────────────────────────
    doc.addPage();
    addHeader('Summary of Documentation');
    doc.moveDown(0.5);

    const sumWidths = [60, 180, 60, 80, 60, 55];
    drawTableRow(['Criterion', 'Name', 'Max Marks', 'Completed', 'Docs', 'Status'], sumWidths, true);

    criteria.forEach((c, idx) => {
      const total = c.subCriteria.length;
      const completed = c.subCriteria.filter((sc) => {
        const s = subMap[sc.id];
        return s && ['submitted', 'verified'].includes(s.status);
      }).length;
      const docs = c.subCriteria.reduce((sum, sc) => sum + (subMap[sc.id]?.documents?.length || 0), 0);
      const status = completed === total && total > 0 ? '✓ Done' : completed > 0 ? 'In Progress' : 'Not Started';
      drawTableRow([c.code, c.name, c.maxMarks, `${completed}/${total}`, docs, status], sumWidths, false, idx % 2 === 1);
    });

    // ── CRITERION PAGES ───────────────────────────────────────
    criteria.forEach((c) => {
      doc.addPage();
      addHeader(`Criterion ${c.id} — ${c.name} (Max: ${c.maxMarks} Marks)`);
      doc.moveDown(0.3);

      c.subCriteria.forEach((sc) => {
        const sub = subMap[sc.id];
        const entries = sub?.formData?.entries || [];
        const docs = sub?.documents || [];

        checkPage(60);
        addSubHeader(`${sc.code} — ${sc.name}`);

        const statusText = sub?.status
          ? sub.status.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
          : 'Not Started';
        doc.fontSize(8).font('Helvetica').fillColor('#888888')
          .text(`Status: ${statusText}`);
        doc.moveDown(0.3);

        if (entries.length > 0) {
          const fieldWidths = [pageWidth * 0.4, pageWidth * 0.6];
          drawTableRow(['Field', 'Value'], fieldWidths, true);

          entries.forEach((entry, ei) => {
            if (entries.length > 1) {
              checkPage(20);
              doc.fontSize(8).font('Helvetica-Oblique').fillColor('#999999')
                .text(`Entry ${ei + 1}`);
              doc.moveDown(0.2);
            }
            Object.entries(entry).forEach(([key, val], fi) => {
              const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
              const value = Array.isArray(val) ? val.join(', ') : String(val || '—');
              drawTableRow([label, value], fieldWidths, false, fi % 2 === 1);
            });
          });
        } else {
          doc.fontSize(9).font('Helvetica-Oblique').fillColor('#999999')
            .text('No data entered for this sub-criterion.');
        }

        if (docs.length > 0) {
          doc.moveDown(0.3);
          doc.fontSize(9).font('Helvetica-Bold').fillColor('#333333')
            .text('Supporting Documents:');
          docs.forEach((d) => {
            const dt = d.uploadedAt ? new Date(d.uploadedAt).toLocaleDateString('en-IN') : '—';
            doc.fontSize(8).font('Helvetica').fillColor('#555555')
              .text(`  • ${d.originalFilename}  (uploaded: ${dt})  [${d.uploadStatus}]`);
          });
        }

        doc.moveDown(0.8);
      });
    });

    // ── HOD SIGNATURE PAGE ────────────────────────────────────
    doc.addPage();
    addHeader('Declaration & Verification');
    doc.moveDown(1);

    doc.fontSize(11).font('Helvetica').fillColor('#333333')
      .text('This is to certify that the information provided in this NAAC documentation report is accurate and has been prepared as per the NAAC guidelines for accreditation purposes.', {
        align: 'justify', lineGap: 4,
      });
    doc.moveDown(1);

    doc.text('All data entries, supporting documents, and records have been reviewed and verified by the Head of Department.', {
      align: 'justify', lineGap: 4,
    });
    doc.moveDown(3);

    // Teacher signature block
    const sigY = doc.y;
    doc.fontSize(10).font('Helvetica').fillColor('#333333');
    doc.text('_________________________', 50, sigY);
    doc.text('_________________________', 320, sigY);
    doc.moveDown(0.3);
    doc.font('Helvetica-Bold');
    doc.text(user.fullName, 50, doc.y);
    doc.text(hod?.fullName || 'Head of Department', 320, doc.y - 14);
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(9).fillColor('#666666');
    doc.text(user.designation || 'Faculty', 50, doc.y);
    doc.text('Head of Department', 320, doc.y - 12);
    doc.moveDown(0.3);
    doc.text(user.department || 'Department', 50, doc.y);
    doc.text(user.department || 'Department', 320, doc.y - 12);

    doc.moveDown(3);

    // Date and place
    doc.fontSize(10).font('Helvetica').fillColor('#333333');
    doc.text(`Date: ${exportDate}`, 50);
    doc.text('Place: ______________________', 50);

    doc.moveDown(2);

    // Official stamp area
    doc.rect(320, doc.y, 180, 80).dash(3).stroke();
    doc.fontSize(8).font('Helvetica').fillColor('#999999')
      .text('Official Stamp / Seal', 370, doc.y - 80 + 30);

    // ── Footer on every page ──────────────────────────────────
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(7).font('Helvetica').fillColor('#AAAAAA')
        .text(
          `college accreditation & document workflow platform  |  ${user.fullName}  |  Page ${i + 1} of ${pages.count}  |  ${exportDate}`,
          50, doc.page.height - 35, { width: pageWidth, align: 'center' }
        );
    }

    doc.end();
  });
}

module.exports = { generateTeacherPdf };

